function to compute skeleton graph from predicted probability space image
morphometrics/morphospaces pull request #7
Opened 2023-01-09 17:46 UTC by MalteMederacke

Split it up into four functions. Are the dependencies ok?

2023-01-10 04:01 UTC, kevinyamauchi requested changes
Thanks, @MalteMederacke - I think this is a good start. I have a few general comments below and then made specific comments inline.

- Can you please add a general function that integrates all of these utility functions to take in the predictions and returns the cleaned up skeleton graph?
- Can you please add tests for each of the utility functions and the integration function described above? You can add a `_tests` module in this directory and put the tests in there. The file and function names should start with `test_` (this is how pytest finds them). Tutorial on pytest: [video](https://www.youtube.com/watch?v=LX2ksGYXJ80), [corresponding materials](https://leemangeophysicalllc.github.io/testing-with-python/) (probably just do the setup and introduction sections for now)
- please use the [numpy style docstrings](https://numpydoc.readthedocs.io/en/latest/format.html) (short summary, parameters, and returns)
- please add type annotations to the function inputs and outputs. these make it clear what the expected types are for the inputs and outputs and can be used by IDEs and other static analysis tools to help make sure the code is correct. https://towardsdatascience.com/type-annotations-in-python-d90990b172dc

2023-01-10 04:01 UTC, kevinyamauchi commented on src/morphospaces/skeleton/prediction_to_skeleton_graph.py
> +    graph_reduced = nx.Graph()
I think we can further simplify the reduced graph.  I think we can make a graph as follows:
- it's nodes are only the end points and branch points.
- we add the simplified edges between the end points and branch points
- we can add the list of coordinates for the nodes that the simplified edges as [edge attributes](https://networkx.org/documentation/stable/reference/generated/networkx.classes.function.set_edge_attributes.html) Eventually, this can be a spline or some other geometric object, but this is a starting points.


What do you think?

2023-01-10 04:50 UTC, kevinyamauchi commented on src/morphospaces/skeleton/prediction_to_skeleton_graph.py
> +import napari_accelerated_pixel_and_object_classification as npps
Also, is this the right import? Should this be: https://github.com/haesleinhuepf/napari-process-points-and-surfaces?

In any case, I would prefer not to depend on that either due to the open3D dependency

2023-01-10 04:51 UTC, kevinyamauchi commented on src/morphospaces/skeleton/prediction_to_skeleton_graph.py
> +    mesh = npps.label_to_surface(skeleton_prediction_image)
It looks like this just uses marching cubes - should be easy to replace: https://github.com/haesleinhuepf/napari-process-points-and-surfaces/blob/a6c9113b4860917cbf6beb2b6c535e9ecced1d25/napari_process_points_and_surfaces/__init__.py#L474-L480

2023-01-10 08:33 UTC, MalteMederacke commented on src/morphospaces/skeleton/prediction_to_skeleton_graph.py
> +        threshold (float): percentage of pixels used.
Yes, that are the right words.

2023-01-10 08:35 UTC, MalteMederacke commented on src/morphospaces/skeleton/prediction_to_skeleton_graph.py
> +    )
Yes, Trimesh distance function is around an order of magnitude or more slower. I mean, its quick to be exchanged and you are right, the number of points is on the smaller side.

2023-01-10 08:42 UTC, MalteMederacke commented on src/morphospaces/skeleton/prediction_to_skeleton_graph.py
> +            sps.append(nx.shortest_path(graph, bp, ep))
Oh, yup, we need to allow for branch point to branch point edges! Good catch

2023-01-10 08:46 UTC, MalteMederacke commented on src/morphospaces/skeleton/prediction_to_skeleton_graph.py
> +    graph_reduced = nx.Graph()
so, you want to simplify the curvature of branches by moving all nodes with degree 2 in edge attributes? We can do that, if big graphs are a problem. Otherwise I would rather add the branch and end points as node attributes and keep all the coordinates in the graph?

2023-01-10 09:36 UTC, kevinyamauchi commented on src/morphospaces/skeleton/prediction_to_skeleton_graph.py
> +    graph_reduced = nx.Graph()
Yes, I would like to simplify the graph such that it just represents the connectivity between branch/end points. On the edges we can store a representation of the actual path of that branch. I suggested a list of the coordinates of the points in the branches as a simple starting point (i.e., don't really have to write any new code). However, I would like to represent the branch trajectories as a spline in the near future. 

I don't think it's very useful to store the nodes that are inside of the branches as a graph. The types of analysis we would want to do on the branches are things like measuring the length, obtaining orthogonal slices to measure diameters, check if the branches are open, etc. All of those things are better achieved with a spline or some other parametric representation.

2023-01-10 15:41 UTC, kevinyamauchi commented on src/morphospaces/skeleton/prediction_to_skeleton_graph.py
> +        )
Are you saying that in the contracted graph, the nodes that your contracted are not present? For example, if you have nodes `(0, 1, 2, 3)` and edges `[(0, 1), (2. 3)]` and you contract nodes 2 to node 0 (i.e., `contracted_nodes(my_graph, 0, 2,)`), it seems to me like you should get a graph  with nodes `(0, 1, 3)` and [(0, 1), (0, 3)]`. As I understand it, the function should be equivalent to removing node 2 and assigning any edges ending at node 2 to node 0.

2023-01-11 15:24 UTC, MalteMederacke commented
I think I should have covered everything

2023-01-16 15:40 UTC, kevinyamauchi reviewed
This is coming along well! Thanks! I have a few clarifying questions below and a couple of nitpicks on style.

2023-01-16 15:40 UTC, kevinyamauchi commented on src/morphospaces/skeleton/prediction_to_skeleton_graph.py
> +        )
I didn't understand your comment [here](https://github.com/morphometrics/morphospaces/pull/7#discussion_r1065813713). Can you explain the purpose of this code block?

Is it possible to simplify the indexing here? It feels a bit convoluted.

2023-01-16 15:40 UTC, kevinyamauchi commented on src/morphospaces/skeleton/prediction_to_skeleton_graph.py
> +        reduced_positions[node] = node_coordinates[node]
I think the dictionary comprehension is more readable here
```suggestion
    reduced_positions = {node: node_coordinates[node] for node in graph_reduced.nodes}
```

2023-01-16 15:40 UTC, kevinyamauchi commented on src/morphospaces/skeleton/prediction_to_skeleton_graph.py
> +    Takes the predicted skeleton, branch points and end points from the
```suggestion
    """Takes the predicted skeleton, branch points and end points from the
```

2023-01-16 15:40 UTC, kevinyamauchi commented on src/morphospaces/skeleton/prediction_to_skeleton_graph.py
> +    Reduce the graph to branch- and end points. Pixels lying inbetween
```suggestion
    """Reduce the graph to branch- and end points. Pixels lying inbetween
```

2023-01-16 15:40 UTC, kevinyamauchi commented on src/morphospaces/skeleton/_tests/test_skeleton.py
> +import raster_geometry as rg
is this a package that we would have to add as a dependency?

2023-01-16 15:40 UTC, kevinyamauchi commented on src/morphospaces/skeleton/_tests/test_skeleton.py
> +    cylinder_image = rg.cylinder(15, 13, 2)
This test could probably also be done using just a rectangular prism rather than adding this dependency.

for example
```
rectangular_prism = np.zeros((20, 20, 20))
rectangular_prism[5:15, 8:12, 8:12] = 1
```

2023-01-16 15:40 UTC, kevinyamauchi commented on src/morphospaces/skeleton/prediction_to_skeleton_graph.py
> +    sps = []
can you please give this a more descriptive name?

2023-01-16 15:40 UTC, kevinyamauchi commented on src/morphospaces/skeleton/prediction_to_skeleton_graph.py
> +    for num_nodes_in_path in sps:
is `num_nodes_in_path` an accurate variable name? based on line 233 above, I would have expected this to be a list of nodes

2023-01-16 15:40 UTC, kevinyamauchi commented on src/morphospaces/skeleton/prediction_to_skeleton_graph.py
> +    # Very slow, maybe do in one step?
how slow is this? I am not super concerned with performance at this stage, but if it prevents us from scaling to a full lung, we should probably improve it.

2025-06-20 08:07 UTC, closed without merging